### ISSUE TITLE
Using gulp-strip-debug with gulp-sourcemaps

### ISSUE THREAD

**Issue by jonathan-soifer** [sindresorhus/gulp-strip-debug#10]
Hi,

I tried using gulp-strip-debug with gulp-sourcemaps and apparently they don't play well together.

Do you have any plans on making it compatible?

Thank you :)

**Comment by sindresorhus** [comment]
I would welcome a pull request, but not really something I have time to implement right now. Would need to be implemented in [`strip-debug`](https://github.com/sindresorhus/strip-debug) first.

https://github.com/sindresorhus/strip-debug/issues/11

**Comment by jonathan-soifer** [comment]
Thank you for the fast reply. I'm not yet proficient with this in order to help unfortunately.

I'm still using it for production: I need the gulp-strip-debug but not the sourcemaps for that :)
