### ISSUE TITLE
Is there a way to preserve alerts?

### ISSUE THREAD

**Issue by wzup** [sindresorhus/gulp-strip-debug#11]
I have a React component that calls `alert("Some info message")` inside a function. The function is called as a `onClick` event handler. Because there is no way to set an inline attribute `onclick="alert('Some info message')"` in React, I have to do it this way:
```
var FooComponent= React.createClass({
    onOptionSelect: function(e) {
        e.preventDefault();
        alert('Some info message.');
        return;
    },
```
So I want to preserve `alert()`s. How to achieve it?

**Comment by wzup** [comment]
```
var arlt = window.alert;
arlt('Some alert message.');
```

**Comment by sindresorhus** [comment]
Don't open an issue in two places. Especially not without cross-linking.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/strip-debug/issues/12
