### ISSUE TITLE
Installation error : stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by ShashiBadhuk** [sindresorhus/gulp-strip-debug#15]
npm install --save-dev gulp-strip-debug

make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/shashi/Documents/Workspace/Videocon/Marketplace/marketplace/node_modules/pioneer/node_modules/bufferutil
gyp ERR! node -v v5.10.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:bufferutil@1.1.0 bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.1.0 Exit status 1

**Comment by sindresorhus** [comment]
The error is not coming from this module.

> /Users/shashi/Documents/Workspace/Videocon/Marketplace/marketplace/node_modules/pioneer/node_modules/**bufferutil**
