### ISSUE TITLE
package doesn't work

### ISSUE THREAD

**Issue by gapsaras** [sindresorhus/gulp-strip-debug#20]
Hello, I'm glad to find this package to solve my problem(just remove `console.log`  from my js files). But it doesn't work, nor outputs any infomation. it should be a `dist` directory in my project, I have no idea how to debug it .
`output`:
> [19:06:05] Using gulpfile ~/ownspace/gulp-demo/gulpfile.js
[19:06:05] Starting 'bye-console'...
[19:06:05] Finished 'bye-console' after 21 ms

`my code`:
```
var gulp = require('gulp');
.....// other gulp related package here
var stripDebug = require('gulp-strip-debug');
gulp.task('bye-console',function(){
    return gulp.src('app/scripts/**/*.js')
        pipe(stripDebug())
        pipe(gulp.dest('dist'))
})
```
Version: "gulp-strip-debug": "^1.1.0"

**Comment by sindresorhus** [comment]
Is there a dist directory if you remove `pipe(stripDebug())` ?

**Comment by gapsaras** [comment]
After remove the `pipe(stripDebug())`, there is no 'dist' directory.

**Comment by sindresorhus** [comment]
So the problem is clearly not with this plugin then.
