### ISSUE TITLE
Add an option to fail and exit with an error code instead of doing the strip

### ISSUE THREAD

**Issue by rbecheras** [sindresorhus/gulp-strip-debug#21]
This option could be named "lint" for example, because it would behave as a linter

**Comment by sindresorhus** [comment]
Would be better to just use a linter then:
https://eslint.org/docs/rules/no-console
https://eslint.org/docs/rules/no-alert
https://eslint.org/docs/rules/no-debugger

**Comment by rbecheras** [comment]
You're right!
Thanks for responding.
