### ISSUE TITLE
console.log is not stripped out

### ISSUE THREAD

**Issue by JiboStore** [sindresorhus/gulp-strip-debug#24]
Hi, I am following the readme exactly, however the generated code does not cause console.log to be removed, indeed all the logs are still printed out.

```
console.log('something')
```

is changed to:
```
    var _console;
    (_console = console).log.apply(_console, arguments);
```

which, if I evaluate, the `console` variable is stored in to `_console` whose log function is then called, thus there is no effect of removing console.log at all

Is there any parameters that I might be missing?

**Comment by sindresorhus** [comment]
`strip-debug` is only able to remove normal `console.log`. It seems like something in your Gulp pipeline is changing the console.log output before it's passed to this plugin.

**Comment by JiboStore** [comment]
Yeah, you are right, the culprit was:

```
    .pipe(babel({
        presets: ['module:metro-react-native-babel-preset']
    }))
```
causing the `(_console = console).log` thus this plugin was unable to strip it..

```
        .pipe(babel({
            presets: ['module:metro-react-native-babel-preset'],
            plugins: ['module:babel-plugin-transform-remove-console']
        }))
```
adding the `babel-plugin-transform-remove-console` solves the problem

Thank you very much for the help!

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/gulp-strip-debug/releases/tag/v4.0.0
