### ISSUE TITLE
FATAL ERROR: JS Allocation failed - process out of memory

### ISSUE THREAD

**Issue by banjankri** [sindresorhus/gulp-strip-debug#9]
Hi,
First of all thanks for all great pieces of work you have done! I have come accross a problem recently using gulp-strip-debug. When trying to apply it to newest select2 lib (version 4.0.0 at the time of posting this) it dies screaming:

FATAL ERROR: JS Allocation failed - process out of memory

Could you please look into it or whether the issue should be raised with the strip-debug tool?

Thanks

**Comment by sindresorhus** [comment]
Sounds like a duplicate of https://github.com/sindresorhus/gulp-strip-debug/issues/7

Try reinstalling to plugin to make sure you're on the latest.

**Comment by banjankri** [comment]
Tried it and worked perfectly, thanks, closing!
